# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gravity
email: panfeihao@gmail.com
description: Panfeihao'blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://panfeihao.github.io" # the base hostname & protocol for your site
twitter_username: panfeihao
github_username:  panfeihao
paginate: 5

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
